---
- name: Refresh apt cache
  apt:
    update_cache: yes

- name: Install packages that should be available
  apt:
    name: "{{ item }}"
  with_items:
    - htop
    - git
    - rlwrap

- name: Set up ufw firewall
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items:
    - 22
    - 80
    - 443
