---
- name: Install prerequisites for the Clojurians Log app
  vars_files:
    - vars/clojurians_log_secrets.yml
  hosts: clojurians_log
  become: true
  vars:
    database_name: "clojurians_log_datomic"
    database_user: "clojurians_log"
    database_password: ""
    database_hostname: "localhost"
    database_port: 5432
    fail2ban_services:
      - name: ssh
        enabled: true
        port: ssh
        filter: sshd
        logpath: /var/log/auth.log
        maxretry: 3
        protocol: tcp
  roles:
    - role: plexus.system-defaults
    - role: jnv.unattended-upgrades

    - role: ANXS.postgresql
      tags: postgresql
      postgresql_databases:
        - name: "{{database_name}}"
      postgresql_users:
        - name: "{{database_user}}"
          pass: "{{database_password}}"
          encrypted: no
      postgresql_user_privileges:
        - name: "{{database_user}}"
          db: "{{database_name}}"
          priv: "ALL"

    - role: ANXS.fail2ban
      tags: fail2ban

    - role: joshualund.ufw
      tags: ufw
      ufw_connection_rate_limits:
        - {port: 22, protocol: tcp}
      ufw_whitelisted_ports:
        - {port: 22, protocol: tcp}
        - {port: 80, protocol: tcp}
        - {port: 443, protocol: tcp}

    - role: ansiblebit.oracle-java
      oracle_java_set_as_default: yes

    - role: plexus.datomic-pro
      tags: datomic
      datomic_pro_version: 0.9.5561.56
