---
- name: Install the app configuration
  template:
    src: templates/config.edn
    dest: "{{ clojure_app_home_dir }}/config.edn"

- name: Create .lein/profiles.clj to load datomic-pro
  template:
    src: templates/profiles.clj.j2
    dest: "{{ clojure_app_home_dir }}/.lein/profiles.clj"

- name: Create SSH public key
  copy:
    content: "{{ clojure_app_ssh_id_rsa_pub }}"
    dest: "{{ clojure_app_home_dir }}/.ssh/id_rsa.pub"
    owner: "{{ clojure_app_user }}"
    group: "{{ clojure_app_user }}"
    mode: 0644

- name: Create SSH private key
  copy:
    content: "{{ clojure_app_ssh_id_rsa }}"
    dest: "{{ clojure_app_home_dir }}/.ssh/id_rsa"
    owner: "{{ clojure_app_user }}"
    group: "{{ clojure_app_user }}"
    mode: 0600

- name: Check out existing logs
  become: "{{ clojure_app_user }}"
  become_method: sudo
  git:
    repo: "git@github.com:plexus/clojurians-log.git"
    dest: "{{ clojure_app_home_dir }}/logs"
    accept_hostkey: yes
    key_file: "{{ clojure_app_home_dir }}/.ssh/id_rsa"
  tags: git-checkout
