---
- name: Install prerequisites
  apt:
    name: "{{ item }}"
  with_items:
    - python2.7
    - python-pip
  tags: rtmbot

- name: Install python dependencies
  pip:
    name: "{{ item }}"
    executable: /usr/bin/pip
  with_items:
    - requests
    - python-daemon
    - pyyaml
    - websocket-client
    - slackclient
    - docopt
    - pystache
    - py-gfm
  tags: rtmbot

- name: Create rtmbot directory
  file:
    path: "{{ clojure_app_home_dir }}/rtmbot"
    state: directory
    owner: "{{ clojure_app_user }}"
    group: "{{ clojure_app_user }}"
  tags: rtmbot

- name: Create rtmbot logs directory
  file:
    path: "{{ clojure_app_home_dir }}/rtmbot/logs"
    state: directory
    owner: "{{ clojure_app_user }}"
    group: "{{ clojure_app_user }}"
  tags: rtmbot

- name: Install run-rtmbot.sh
  template:
    src: templates/run-rtmbot.sh.j2
    dest: "{{ clojure_app_home_dir }}/rtmbot/run-rtmbot.sh"
    owner: "{{ clojure_app_user }}"
    group: "{{ clojure_app_user }}"
    mode: 0755
  tags: rtmbot

- name: Install rtmbot.conf
  template:
    src: templates/rtmbot.conf.j2
    dest: "{{ clojure_app_home_dir }}/rtmbot/rtmbot.conf"
    owner: "{{ clojure_app_user }}"
    group: "{{ clojure_app_user }}"
    mode: 0644
  tags: rtmbot

- name: Upload rtmbot Systemd startup script
  template:
    src: templates/rtmbot.service.j2
    dest: "/etc/systemd/system/rtmbot.service"
  tags: rtmbot

- name: Start the rtmbot
  service:
    name: rtmbot
    state: started
    enabled: yes
  tags: rtmbot
